#!/usr/bin/env bash
#script that pings an IP address passed as an argument.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Get IP address from 1st argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 $ip_address

#if pings were successful, otherwise fail
#exit
if [ $? -eq 0 ]
then
  echo "Host $ip_address is on the network."
  exit 0
else
  echo "Host $ip_address is not reachable."
  exit 1
fi
