#!/usr/bin/env bash
#stop the processes of last file

target="4-to_infinity_and_beyond"
pid=$(pgrep -f "$target")
kill "$pid"

#anther answers>>
#kill "$(pgrep -f "4-to_infinity_and_beyond")"
#kill "$(ps -x | pgrep -f beyond)"

