#!/usr/bin/env bash
#Display "best school" using while and if elif
# "bad luck" for 4th iteration
# "good luck" for 8 iteration
# "best school" else

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 3 ];
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done